name       : rambox-pro
version    : 1.4.0
release    : 5
source     :
    - https://github.com/ramboxapp/download/releases/download/v1.4.0/RamboxPro-1.4.0-linux-x64.deb : 468713c8e1437722c9b2b2fbc6fc7d81bc6a85be5326bddd995a02393c7b6b26
homepage   : https://rambox.pro
license    : https://rambox.pro/#eula
strip      : no
component  : system.utils
summary    : Rambox
description: |
    The all-in-one workspace browser.
builddeps  :
  - libgtk-3
  - libnotify
  - libnss
  - libxtst
  - xdg-utils
  - libappindicator
  - libsecret
rundeps    :
  - libgtk-3
  - libnotify
  - libnss
  - libxtst
  - xdg-utils
  - libappindicator
  - libsecret
setup      : |
    ar xf $sources/RamboxPro-${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir
    cp -R opt $installdir/opt/
    cp -R usr $installdir/usr/