name       : skype
version    : 8.65.0.76
release    : 10
source     :
    - https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.65.0.76_amd64.deb : 45f5add7369eda359a50ed3bc179aa1f6757391648d02ff1bd5ffa9331db6f2d
homepage   : https://www.skype.com/
license    : Copyright (c) 2019 Skype and/or Microsoft
strip      : no
component  : network.im
summary    : Skype
description: |
    Skype keeps you together. Call, message and share with others.
builddeps  :
    - libnss
    - libatk
    - glibc
    - libcairo
    - pycups
    - libgcc
    - libgtk-3
    - libnspr
    - libsecret
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxrandr
    - libxrender
    - libstdc++
    - libdbusmenu
    - gnome-keyring
    - libxtst
rundeps    :
    - libnss
    - libatk
    - glibc
    - libcairo
    - pycups
    - libgcc
    - libgtk-3
    - libnspr
    - libsecret
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxrandr
    - libxrender
    - libstdc++
    - libdbusmenu
    - gnome-keyring
    - libxtst
setup      : |
    ar xf $sources/skypeforlinux_${version}_amd64.deb
    tar xf data.tar.xz
install    : |
    mkdir -p $installdir/usr/
    cp -R opt $installdir/opt/
    cp -R usr/{bin,share} $installdir/usr/
