name       : plexmediaserver_1.20.5.3600
version    : 
release    : 1
source     :
    - https://downloads.plex.tv/plex-media-server-new/1.20.5.3600-47c0d9038/debian/plexmediaserver_1.20.5.3600-47c0d9038_amd64.deb : be1068dcc439e727df18e8cec61d4185b46a7752a26979b4b55bcbad0c163807
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
