name       : android-studio-ide-201.6858069
version    : linux
release    : 1
source     :
    - https://dl.google.com/dl/android/studio/ide-zips/4.1.0.19/android-studio-ide-201.6858069-linux.tar.gz : 4b9521fc4a6313ad65ff3e14b0f3fb50427d464fe14227555565f46e0ffad202
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install
