name       : insync_3.3.0.40894
version    : 
release    : 1
source     :
    - http://s.insynchq.com/builds/insync_3.3.0.40894-bionic_amd64.deb : 61548867aa97869b26e8d67c7382d237a25822aefee1a7294dcdff92b2cb0b7d
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
