name       : ramboxpro-1.4.0-linux
version    : 
release    : 1
source     :
    - https://github.com/ramboxapp/download/releases/download/v1.4.0/RamboxPro-1.4.0-linux-x64.deb : 468713c8e1437722c9b2b2fbc6fc7d81bc6a85be5326bddd995a02393c7b6b26
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
