name       : libssl1.1_1.1.1f
version    : 
release    : 1
source     :
    - http://mirrors.kernel.org/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb : 09ee28588a1fb5613ddc6c26a992d5a76931b3cf22c022930da413a5e580599e
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
