name       : google-chrome-stable_86.0.4240.75
version    : 
release    : 1
source     :
    - https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_86.0.4240.75-1_amd64.deb : 1fbead737a5f46086b0e5736333516257bc23702f4ff686ac48c6580daec3a9e
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
