name       : plexmediaserver_1.20.3.3437
version    : 
release    : 1
source     :
    - http://downloads.plex.tv/plex-media-server-new/1.20.3.3437-f1f08d65b/debian/plexmediaserver_1.20.3.3437-f1f08d65b_amd64.deb : 32454e0b3129deb2c9548280a325d5135539fac45e7e9c7c369ae5a6c8e87e2d
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
