name       : 
version    : skypeforlinux_8.66.0
release    : 1
source     :
    - https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.66.0.74_amd64.deb : 0ed958586e9bc99e2f91a3803314b059761eb21658f4dc85e945392347fe7785
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
