name       : emby-server
version    : deb_4.5.2
release    : 1
source     :
    - https://github.com/MediaBrowser/Emby.Releases/releases/download/4.5.2.0/emby-server-deb_4.5.2.0_amd64.deb : 54df3e695a5444de7708aeaac4a28a78c093edb62c66b0b6b9d67e2da01197a2
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
