name       : rambox-0.7.7-linux
version    : 
release    : 1
source     :
    - https://github.com/ramboxapp/community-edition/releases/download/0.7.7/Rambox-0.7.7-linux-amd64.deb : a99bf982ba01925a60b5d5b6ea05e39bfd52bdf3261f7c117b24bdb98223322e
license    : GPL-2.0-or-later # CHECK ME
component  : PLEASE FILL ME IN
summary    : PLEASE FILL ME IN
description: |
    PLEASE FILL ME IN
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
