name       : rambox
version    : 0.7.7
release    : 3
source     :
    - https://github.com/ramboxapp/community-edition/releases/download/0.7.7/Rambox-0.7.7-linux-amd64.deb : a99bf982ba01925a60b5d5b6ea05e39bfd52bdf3261f7c117b24bdb98223322e
homepage   : https://rambox.pro
license    : https://rambox.pro/#eula
component  : system.utils
summary    : Rambox
description: |
    Free and Open Source messaging and emailing app that combines common web applications into one.
builddeps  :
  - libgtk-3
  - libnotify
  - libnss
  - libxtst
  - xdg-utils
  - libappindicator
  - libsecret
rundeps    :
  - libgtk-3
  - libnotify
  - libnss
  - libxtst
  - xdg-utils
  - libappindicator
  - libsecret
setup      : |
    ar xf $sources/Rambox-${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir
    cp -R opt $installdir/opt/
    cp -R usr $installdir/usr/