name       : protonmail-bridge
version     : 1.3.3
release     : 0
license     : MIT
source      :
    - https://protonmail.com/download/protonmail-bridge_1.3.3-1_amd64.deb : 5265f10ec78a1051ed816910f55aa8b1ebfca53f747df38dc8af27f214105ca0
component   : network.mail
strip       : no
summary     : The Bridge is an application that runs on your computer in the background and seamlessly encrypts and decrypts your mail as it enters and leaves your computer.
description : |
    The Bridge is an application that runs on your computer in the background and seamlessly encrypts and decrypts your mail as it enters and leaves your computer.
builddeps    :
    - libglvnd
rundeps      :
    - qt5-base
    - qt5-multimedia
    - libsecret
    - dejavu-fonts-ttf
setup       : |
    ar xf $sources/protonmail-bridge_${version}-1_amd64.deb
    tar xf data.tar.xz
install     : |
    mkdir -p $installdir
    cp -R usr $installdir/usr/
