name       : google-chrome-stable
version    : 84.0.4147.125
release    : 17
source     :
    - https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_84.0.4147.125-1_amd64.deb : 1cb13f135c51a155dd86846457254ebea986a2b34e87b8236cc14df2e74e76b9
homepage   : https://www.google.com/chrome/
license    : EULA
strip      : no
component  : network.web.browser
summary    : Google Chrome
description: |
    Google Chrome is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.
builddeps  :
    - libxscrnsaver
    - gconf
    - binutils
    - liberation-fonts-ttf
    - libappindicator
    - libatk
    - libgcc
    - libcairo
    - pycups
    - libdbusmenu
    - libgtk-3
    - libnspr
    - libnss
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxtst
    - wget
    - xdg-utils
rundeps    :
    - libxscrnsaver
    - gconf
    - binutils
    - liberation-fonts-ttf
    - libappindicator
    - libatk
    - libgcc
    - libcairo
    - pycups
    - libdbusmenu
    - libgtk-3
    - libnspr
    - libnss
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxtst
    - wget
    - xdg-utils
setup      : |
    ar xf $sources/google-chrome-stable_${version}*
    tar xf data.tar*
build      : |
    chown root:root opt/google/chrome/chrome-sandbox
    chmod 4755 opt/google/chrome/chrome-sandbox
install    : |
    mkdir -p $installdir
    install -D -d -m 00755 $installdir/usr/bin
    install -D -d -m 00644 $installdir/usr/share
    mkdir -p $installdir/usr
    cp -R opt $installdir/
    cp -R usr/{bin,share} $installdir/usr/