name       : megasync
version    : 4.3.5
release    : 6
source     :
    - https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/megasync-xUbuntu_20.04_amd64.deb : 4ab22ae955b0af41873e68fdb84cd199e0a20940fb1a37165c58a2d3c73fe5e0
    - https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/nautilus-megasync-xUbuntu_20.04_amd64.deb : e23af051fa50febc2f49ae4bd61ece059e7b6c6f11adfe119cdc20bc1a1ac75a
    - https://mega.nz/linux/MEGAsync/xUbuntu_20.04/amd64/dolphin-megasync-xUbuntu_20.04_amd64.deb : 2db5996d51b8b6b7b3b44e53c10b3da5a2c8348f456a0133dbc1175beb8dea8a
license    : © MEGA 2020 All rights reserved
strip      : no
component  : network.clients
summary    : Sync your files to your Mega account.
description: |
    Easy automated syncing between your computers and your MEGA cloud drive
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libcares)
    - pkgconfig(libcurl)
    - pkgconfig(libmediainfo)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(libsodium)
    - pkgconfig(libuv)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(sqlite3)
    - pkgconfig(zlib)
    - cryptopp-devel
rundeps    :
    - cryptopp-devel
    - libsodium
    - libraw
    - libraw-utils
    - qt5-x11extras
setup      : |
    ar xf $sources/megasync*
    tar xf data.tar*
install    : |
    mkdir -p $installdir
    cp -R etc $installdir/etc/
    cp -R usr $installdir/usr/