name       : google-chrome-beta
version    : 85.0.4183.83
release    : 14
source     :
    - https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-beta/google-chrome-beta_85.0.4183.83-1_amd64.deb : a6d250cde2391abca6749417ed6d6308022d1f779ccdc37261fcaf0b0e3cd58a
homepage   : https://www.google.com/chrome/
license    : EULA
strip      : no
component  : network.web.browser
summary    : Google Chrome Beta
description: |
    Google Chrome is a browser that combines a minimal design with sophisticated technology to make the web faster, safer, and easier.
builddeps  :
    - libxscrnsaver
    - gconf
    - binutils
    - liberation-fonts-ttf
    - libappindicator
    - libatk
    - libgcc
    - libcairo
    - pycups
    - libdbusmenu
    - libgtk-3
    - libnspr
    - libnss
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxtst
    - wget
    - xdg-utils
rundeps    :
    - libxscrnsaver
    - gconf
    - binutils
    - liberation-fonts-ttf
    - libappindicator
    - libatk
    - libgcc
    - libcairo
    - pycups
    - libdbusmenu
    - libgtk-3
    - libnspr
    - libnss
    - libx11
    - libxcb
    - libxcomposite
    - libxcursor
    - libxdamage
    - libxext
    - libxfixes
    - libxi
    - libxrandr
    - libxrender
    - libxtst
    - wget
    - xdg-utils
setup      : |
    ar xf $sources/google-chrome-beta_${version}-1_amd64.deb
    tar xf data.tar.xz
build      : |
    chown root:root opt/google/chrome-beta/chrome-sandbox
    chmod 4755 opt/google/chrome-beta/chrome-sandbox
install    : |
    mkdir -p $installdir
    install -D -d -m 00755 $installdir/usr/bin
    install -D -d -m 00644 $installdir/usr/share
    mkdir -p $installdir/usr
    cp -R opt $installdir/
    cp -R usr/{bin,share} $installdir/usr/