name       : libhandy
version    : 1.0.0
release    : 2
source     :
    - https://gitlab.gnome.org/GNOME/libhandy/-/archive/1.0.0/libhandy-1.0.0.tar.gz : dc1fff98cbc72a492d1adb489ee1b00e43ab4ac14c983c855ef3df435bbbda27
license    : LGPL-2.1+
component  : desktop.gnome
summary    : The Handy Library
description: |
    The Handy Library
builddeps  :
   - pkgconfig(gladeui-2.0)
   - pkgconfig(glib-2.0)
   - pkgconfig(gio-2.0)
   - pkgconfig(gmodule-2.0)
   - pkgconfig(gtk+-3.0)
   - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install