name       : enpass
version    : 6.5.1.723
release    : 3
source     :
    - http://repo.sinew.in/pool/main/e/enpass/enpass_6.5.1.723_amd64.deb : d9bb408fa2253ce44ab5396898f7db13291ce23ae58964f4a27ade38bd5067bf
homepage   : https://enpass.io
license    : Custom
strip      : no
component  : security
summary    : A multiplatform password manager
description: |
    A multiplatform password manager
builddeps  :
    - libxscrnsaver
    - lsof
    - libglvnd
rundeps    :
    - libxscrnsaver
    - lsof
    - libglvnd
setup      : |
    ar xf $sources/enpass_${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir
    cp -R opt $installdir/opt/
    cp -R usr $installdir/usr/