name       : plexmediaserver
version    : 1.20.3.3437
release    : 17
source     :
    - http://downloads.plex.tv/plex-media-server-new/1.20.3.3437-f1f08d65b/debian/plexmediaserver_1.20.3.3437-f1f08d65b_amd64.deb : 32454e0b3129deb2c9548280a325d5135539fac45e7e9c7c369ae5a6c8e87e2d
homepage   : https://plex.tv
license    : https://plex.tv/legal
strip      : no
component  : multimedia.video
summary    : Plex Media Server
description: |
    Plex organizes all of your personal media so you can easily access and enjoy it.
builddeps  :
  - binutils
rundeps    :
  - binutils
setup      : |
    ar xf $sources/plexmediaserver_${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir/usr
    mkdir -p $installdir/opt
    install -Dm00644 $pkgfiles/plexmediaserver.conf $installdir/%libdir%/sysusers.d/plexmediaserver.conf
    install -Dm00644 $pkgfiles/plexmediaserver.tmpfile $installdir/%libdir%/tmpfiles.d/plexmediaserver.conf
    install -Dm00644 $pkgfiles/plexmediaserver.service $installdir/%libdir%/systemd/system/plexmediaserver.service
    cp -R usr/share $installdir/usr/
    cp -R usr/lib/plexmediaserver $installdir/opt/