name       : plexmediaserver
version    : 1.20.1.3252
release    : 16
source     :
    - https://downloads.plex.tv/plex-media-server-new/1.20.1.3252-a78fef9a9/debian/plexmediaserver_1.20.1.3252-a78fef9a9_amd64.deb : f83fab45fad1603adf12b12689e90d38f06a383f1fd7a703b0b9cf2e3489e701
homepage   : https://plex.tv
license    : https://plex.tv/legal
strip      : no
component  : multimedia.video
summary    : Plex Media Server
description: |
    Plex organizes all of your personal media so you can easily access and enjoy it.
builddeps  :
  - binutils
rundeps    :
  - binutils
setup      : |
    ar xf $sources/plexmediaserver_${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir/usr
    mkdir -p $installdir/opt
    install -Dm00644 $pkgfiles/plexmediaserver.conf $installdir/%libdir%/sysusers.d/plexmediaserver.conf
    install -Dm00644 $pkgfiles/plexmediaserver.tmpfile $installdir/%libdir%/tmpfiles.d/plexmediaserver.conf
    install -Dm00644 $pkgfiles/plexmediaserver.service $installdir/%libdir%/systemd/system/plexmediaserver.service
    cp -R usr/share $installdir/usr/
    cp -R usr/lib/plexmediaserver $installdir/opt/