name       : plexmediaserver
version    : 1.20.5.3600
release    : 19
source     :
    - https://downloads.plex.tv/plex-media-server-new/1.20.5.3600-47c0d9038/debian/plexmediaserver_1.20.5.3600-47c0d9038_amd64.deb : be1068dcc439e727df18e8cec61d4185b46a7752a26979b4b55bcbad0c163807
homepage   : https://plex.tv
license    : https://plex.tv/legal
strip      : no
component  : multimedia.video
summary    : Plex Media Server
description: |
    Plex organizes all of your personal media so you can easily access and enjoy it.
builddeps  :
  - binutils
rundeps    :
  - binutils
setup      : |
    ar xf $sources/plexmediaserver_${version}*
    tar xf data.tar*
install    : |
    mkdir -p $installdir/usr
    mkdir -p $installdir/opt
    install -Dm00644 $pkgfiles/plexmediaserver.conf $installdir/%libdir%/sysusers.d/plexmediaserver.conf
    install -Dm00644 $pkgfiles/plexmediaserver.tmpfile $installdir/%libdir%/tmpfiles.d/plexmediaserver.conf
    install -Dm00644 $pkgfiles/plexmediaserver.service $installdir/%libdir%/systemd/system/plexmediaserver.service
    cp -R usr/share $installdir/usr/
    cp -R usr/lib/plexmediaserver $installdir/opt/