name       : softmaker-office-2021
version    : 1020
release    : 3
source     :
    - https://www.softmaker.net/down/softmaker-office-2021_1020-01_amd64.deb : 85db610e912538a3085bf594d8d2829f7a687af69f7846e9dbb18326672feaf4
homepage   : https://www.softmaker.com/
license    : Copyright © 2020 SoftMaker
strip      : no
component  : office
summary    : SoftMaker Office is a complete office suite.
description: |
    SoftMaker Office is powerful and fast, and reads and writes Microsoft Office documents flawlessly. It comes with the TextMaker word processor, the spreadsheet program PlanMaker and the presentations software Presentations.
builddeps  :
    - libnih
    - libx11
    - libxmu
    - libxext
    - libxrender
    - libxrandr
    - python-pycurl
    - libstdc++
    - libglu
rundeps    :
    - libnih
    - libx11
    - libxmu
    - libxext
    - libxrender
    - libxrandr
    - python-pycurl
    - libstdc++
    - libglu
setup      : |
    ar xf $sources/softmaker-office-2021_${version}-01_amd64.deb
    tar xf data.tar.xz
install    : |
    mkdir -p $installdir/usr/bin
    mkdir -p $installdir/usr/lib
    mkdir -p $installdir/usr/share
    cp -R usr/bin $installdir/usr/
    cp -R usr/lib $installdir/usr/
    cp -R usr/share/{applications,doc,lintian,mime,office2021,pixmaps} $installdir/usr/share/
    rm -rf $installdir/usr/share/applications/planmaker-2021.desktop
    rm -rf $installdir/usr/share/applications/presentations-2021.desktop
    rm -rf $installdir/usr/share/applications/textmaker-2021.desktop
    cp $pkgfiles/*.png $installdir/usr/share/office2021/
    cp $pkgfiles/*.desktop $installdir/usr/share/applications/