name       : android-studio
version    : 4.1.1
release    : 10
source     :
    - https://dl.google.com/dl/android/studio/ide-zips/4.1.1.0/android-studio-ide-201.6953283-linux.tar.gz : 68032184959c54576f119b7c7c8ded175d848374f3954fa450530d78260dd68b
homepage   : https://developer.android.com/studio/
license    : Apache-2.0
strip      : no
component  : programming
summary    : Android Studio
description: |
    Android development environment based on IntelliJ IDEA.
builddeps  :
  - bzip2-32bit
  - openjdk-8
  - libstdc++-32bit
  - ncurses-32bit
  - zlib-32bit
rundeps    :
  - bzip2-32bit
  - openjdk-8
  - libstdc++-32bit
  - ncurses-32bit
  - zlib-32bit
setup      : |
    tar xf $sources/android-studio-ide*
install    : |
    mkdir -p $installdir/usr/share/applications/
    mkdir -p $installdir/opt/android-studio
    echo -e '[Desktop Entry]\nVersion=1.0\nType=Application\nName=Android Studio\nIcon=/opt/android-studio/bin/studio.png\nExec=sh /opt/android-studio/bin/studio.sh\nComment=IDE for Android Development\nCategories=Development;IDE;\nTerminal=false\nStartupWMClass=jetbrains-studio' | tee $installdir/usr/share/applications/android-studio.desktop
    cp -R android-studio/* $installdir/opt/android-studio